export const keys = [
    "a",
    "z",
    "e",
    "r",
    "t",
    "y",
    "u",
    "i",
    "o",
    "p",
    "q",
    "s",
    "d",
    "f",
    "g",
    "h",
    "j",
    "k",
    "l",
    "m",
    "w",
    "x",
    "c",
    "v",
    "b",
    "n",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "&",
    "'",
    "ç",
    "!",
    "?",
    ",",
    ".",
    ";",
    "/",
    ":",
    "+",
    "=",
    "%",
    "$",
    "*",
    "€",
    "-",
    " ",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "0",
    "`",
    "~"
];
export const ignoredKeys = ["Shift", "Alt", "ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight", "Meta", "Control", "Tab", "`"];


export const sentences = [
    "I'm hungry",
    "Let me eat!",
    "What is the subject of your PFE?",
    "Help, the cat is too cute",
    "A little 7/7 for this exercise maybe?",
    "yup yup, everything with typescript",
    "I love React",
    "Let me kill this fucking timer",
    "I'm the best",
    "Do you want to build a snowman?",
    "Please come and play with me",
    "'Cause I, I, I'm in the stars tonight",
    "So watch me bring the fire and set the night alight",
    " Shoes on, get up in the morn'",
    "Cup of milk, let's rock and roll",
    "King Kong, kick the drum",
    "Rolling on like a Rolling Stone",
    "Sing song when I'm walkin' home",
    "Jump up to the top, LeBron",
    "Ding - dong, call me on my phone",
    "Ice tea and a game of ping pong",
    "This is gettin' heavy, can you hear the bass boom? I'm ready(Woo - hoo)",
    "Life is sweet as honey, yeah, this beat cha - ching like money, huh",
    "Disco overload, I'm into that, I'm good to go",
    "I'm diamond, you know I glow up",
    "Hey, so let's go",
    "'Cause I, I, I'm in the stars tonight",
    "So watch me bring the fire and set the night alight(Hey)",
    "Shinin' through the city with a little funk and soul",
    "So I'ma light it up like dynamite, woah-oh-oh",
    "Bring a friend, join the crowd, whoever wanna come along",
    "Word up, talk the talk, just move like we off the wall",
    "Day or night, the sky's alight, so we dance to the break of dawn (Hey)",
    "Ladies and gentlemen, I got the medicine so you should keep ya eyes on the ball",
    "Huh, this is gettin' heavy, can you hear the bass boom? I'm ready(Woo - hoo)",
    "Life is sweet as honey, yeah, this beat cha - ching like money, huh",
    "Disco overload, I'm into that, I'm good to go",
    "I'm diamond, you know I glow up",
    "Let's go",
    "'Cause I, I, I'm in the stars tonight",
    "So watch me bring the fire and set the night alight(Hey)",
    "Shinin' through the city with a little funk and soul",
    "So I'ma light it up like dynamite, woah-oh-oh",
    "Dyn - na - na - na, na - na - na - na - na, na - na - na, life is dynamite",
    "Dyn - na - na - na, na - na - na - na - na, na - na - na, life is dynamite",
    "Shinin' through the city with a little funk and soul",
    "So I'ma light it up like dynamite, woah-oh-oh",
    "'Cause I, I, I'm in the stars tonight",
    "So watch me bring the fire and set the night alight",
    "Shinin' through the city with a little funk and soul",
    "So I'ma light it up like dynamite",
    "(This is ah) 'Cause I, I, I'm in the stars tonight",
    "So watch me bring the fire and set the night alight(Alight, oh)",
    "Shinin' through the city with a little funk and soul",
    "So I'ma light (Light) it (It) up (Up) like (Like) dynamite (Dynamite), woah-oh-oh",
    "Dyn - na - na - na, na - na - na - na - na, na - na - na, life is dynamite(Life is dynamite)",
    "Dyn - na - na - na, na - na - na - na - na, na - na - na, life is dynamite(Oh)",
    "Shinin' through the city with a little funk and soul",
    "So I'ma light it up like dynamite, woah-oh-oh"
]